Traceback (most recent call last):
  File "C:\Users\ibhan\miniconda3\envs\mfbook_310\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\ibhan\miniconda3\envs\mfbook_310\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\ibhan\miniconda3\envs\mfbook_310\lib\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\ibhan\miniconda3\envs\mfbook_310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\ibhan\miniconda3\envs\mfbook_310\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\ibhan\miniconda3\envs\mfbook_310\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\ibhan\miniconda3\envs\mfbook_310\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
_ = mpak.invert(baseline,                  # Invert calls the target instrument device                   
                targets = target_simple,                   
                instruments=instruments_simple,
                
                DefaultImpuls=20,      # The default impulse instrument variables 
                defaultconv=2000.0,    # Convergergence criteria for targets
                varimpulse=False,      # Changes in instruments in each iteration are carried over to the future
                nonlin=3,              # If no convergence in 15 iteration recalculate jacobi 
                silent=1,              # Don't show iteration output (try 1 for showing)
                maxiter = 3000,
                progressbar = True)

------------------


Traceback [1;36m(most recent call last)[0m:

[0m  File [0;32m~\miniconda3\envs\mfbook_310\lib\site-packages\IPython\core\interactiveshell.py:3508[0m in [0;35mrun_code[0m
    exec(code_obj, self.user_global_ns, self.user_ns)[0m

[0m  Cell [0;32mIn[8], line 1[0m
    _ = mpak.invert(baseline,                  # Invert calls the target instrument device[0m

[1;36m  File [1;32mC:\modelflow2\modelflow\modelclass.py:7065[1;36m in [1;35minvert[1;36m
[1;33m    from modelinvert import targets_instruments[1;36m

[1;36m  File [1;32mC:\modelflow2\modelflow\modelinvert.py:113[1;36m[0m
[1;33m    def jacobi(2020)(self,per,delay=None):[0m
[1;37m               ^[0m
[1;31mSyntaxError[0m[1;31m:[0m invalid syntax


