Traceback (most recent call last):
  File "C:\Users\ibhan\Anaconda3\envs\mf39new\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\ibhan\Anaconda3\envs\mf39new\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\ibhan\Anaconda3\envs\mf39new\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\ibhan\Anaconda3\envs\mf39new\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\ibhan\Anaconda3\envs\mf39new\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\ibhan\Anaconda3\envs\mf39new\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\ibhan\Anaconda3\envs\mf39new\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\ibhan\Anaconda3\envs\mf39new\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
all_about_ago = GrabWfModel(r'wfs\agosoln.wf1', 
                    eviews_run_lines= ago_eviews_run_lines,
                    country_trans    =  ago_trans,
                    make_fitted = True,        # make equatios for fitted values of stocastic equations 
                    do_add_factor_calc=True,   # Calculate the add factors which makes the stocastic equations match    
                    fit_start = 2000,          # Start of calculation of fittet model in baseline (to have some historic values) 
                    fit_end   = None           # end of calc for fittted model, if None taken from mdmfsa options  
                    ) 
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
File [1;32mC:\modelflow2\modelflow\modelgrabwf2.py:48[0m, in [0;36mwf1_to_wf2[1;34m(filename, modelname, eviews_run_lines)[0m
[0;32m     47[0m [38;5;28;01mtry[39;00m:
[1;32m---> 48[0m     [38;5;28;01mimport[39;00m [38;5;21;01mpyeviews[39;00m [38;5;28;01mas[39;00m [38;5;21;01mevp[39;00m
[0;32m     49[0m [38;5;28;01mexcept[39;00m:

[1;31mModuleNotFoundError[0m: No module named 'pyeviews'

During handling of the above exception, another exception occurred:

[1;31mException[0m                                 Traceback (most recent call last)
Input [1;32mIn [4][0m, in [0;36m<cell line: 1>[1;34m()[0m
[1;32m----> 1[0m all_about_ago [38;5;241m=[39m [43mGrabWfModel[49m[43m([49m[38;5;124;43mr[39;49m[38;5;124;43m'[39;49m[38;5;124;43mwfs[39;49m[38;5;124;43m\[39;49m[38;5;124;43magosoln.wf1[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m
[0;32m      2[0m [43m                    [49m[43meviews_run_lines[49m[38;5;241;43m=[39;49m[43m [49m[43mago_eviews_run_lines[49m[43m,[49m
[0;32m      3[0m [43m                    [49m[43mcountry_trans[49m[43m    [49m[38;5;241;43m=[39;49m[43m  [49m[43mago_trans[49m[43m,[49m
[0;32m      4[0m [43m                    [49m[43mmake_fitted[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;28;43;01mTrue[39;49;00m[43m,[49m[43m        [49m[38;5;66;43;03m# make equatios for fitted values of stocastic equations [39;49;00m
[0;32m      5[0m [43m                    [49m[43mdo_add_factor_calc[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m,[49m[43m   [49m[38;5;66;43;03m# Calculate the add factors which makes the stocastic equations match    [39;49;00m
[0;32m      6[0m [43m                    [49m[43mfit_start[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;241;43m2000[39;49m[43m,[49m[43m          [49m[38;5;66;43;03m# Start of calculation of fittet model in baseline (to have some historic values) [39;49;00m
[0;32m      7[0m [43m                    [49m[43mfit_end[49m[43m   [49m[38;5;241;43m=[39;49m[43m [49m[38;5;28;43;01mNone[39;49;00m[43m           [49m[38;5;66;43;03m# end of calc for fittted model, if None taken from mdmfsa options  [39;49;00m
[0;32m      8[0m [43m                    [49m[43m)[49m

File [1;32m<string>:16[0m, in [0;36m__init__[1;34m(self, filename, modelname, eviews_run_lines, model_all_about, start, end, country_trans, country_df_trans, make_fitted, fit_start, fit_end, do_add_factor_calc, test_frml)[0m

File [1;32mC:\modelflow2\modelflow\modelgrabwf2.py:175[0m, in [0;36mGrabWfModel.__post_init__[1;34m(self)[0m
[0;32m    172[0m     [38;5;28mself[39m[38;5;241m.[39mrawmodel_org [38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mtest_frml 
[0;32m    173[0m [38;5;28;01melse[39;00m:     
[0;32m    174[0m [38;5;66;03m# breakpoint()[39;00m
[1;32m--> 175[0m     wf2name,[38;5;28mself[39m[38;5;241m.[39mmodelname  [38;5;241m=[39m [43mwf1_to_wf2[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mfilename[49m[43m [49m[43m,[49m[43mmodelname[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mmodelname[49m[43m,[49m[43meviews_run_lines[49m[38;5;241;43m=[39;49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43meviews_run_lines[49m[43m)[49m 
[0;32m    176[0m     [38;5;28mself[39m[38;5;241m.[39mmodel_all_about [38;5;241m=[39m wf2_to_clean(wf2name,modelname[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mmodelname)
[0;32m    178[0m     [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m'[39m[38;5;130;01m\n[39;00m[38;5;124mProcessing the model:[39m[38;5;132;01m{[39;00m[38;5;28mself[39m[38;5;241m.[39mmodelname[38;5;132;01m}[39;00m[38;5;124m'[39m,flush[38;5;241m=[39m[38;5;28;01mTrue[39;00m)

File [1;32mC:\modelflow2\modelflow\modelgrabwf2.py:50[0m, in [0;36mwf1_to_wf2[1;34m(filename, modelname, eviews_run_lines)[0m
[0;32m     48[0m     [38;5;28;01mimport[39;00m [38;5;21;01mpyeviews[39;00m [38;5;28;01mas[39;00m [38;5;21;01mevp[39;00m
[0;32m     49[0m [38;5;28;01mexcept[39;00m:
[1;32m---> 50[0m     [38;5;28;01mraise[39;00m [38;5;167;01mException[39;00m([38;5;124m'[39m[38;5;124mYou have not pyeviews installed try:[39m[38;5;130;01m\n[39;00m[38;5;124m'[39m[38;5;241m+[39m
[0;32m     51[0m                     [38;5;124m'[39m[38;5;124m!conda install pyeviews -c conda-forge -y[39m[38;5;124m'[39m)
[0;32m     52[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpathlib[39;00m [38;5;28;01mimport[39;00m Path
[0;32m     53[0m wfpath [38;5;241m=[39m Path(filename)

[1;31mException[0m: You have not pyeviews installed try:
!conda install pyeviews -c conda-forge -y
Exception: You have not pyeviews installed try:
!conda install pyeviews -c conda-forge -y

